#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"
DEV_DIST_DIR="$ROOT_DIR/dist-dev"

: "${DEV_SUPABASE_URL:?DEV_SUPABASE_URL is required}"
: "${DEV_SUPABASE_PUBLISHABLE_KEY:?DEV_SUPABASE_PUBLISHABLE_KEY is required}"

# Start from the exact production-safe artifact so DEV cannot accidentally publish
# repository internals such as SQL, docs, tests, or dev tools.
bash "$ROOT_DIR/scripts/build-production.sh"
bash "$ROOT_DIR/scripts/verify-production.sh"

rm -rf "$DEV_DIST_DIR"
mkdir -p "$DEV_DIST_DIR"
cp -a "$DIST_DIR/." "$DEV_DIST_DIR/"

python3 - "$DEV_DIST_DIR/todayforest-supabase-config.js" <<'PY'
from pathlib import Path
import json
import os
import sys

path = Path(sys.argv[1])
url = os.environ["DEV_SUPABASE_URL"].strip()
key = os.environ["DEV_SUPABASE_PUBLISHABLE_KEY"].strip()

if not url.startswith("https://") or ".supabase.co" not in url:
    raise SystemExit("DEV_SUPABASE_URL does not look like a Supabase project URL")
if not key.startswith("sb_publishable_"):
    raise SystemExit("DEV_SUPABASE_PUBLISHABLE_KEY must be a publishable browser key")

path.write_text(
    "// Generated by scripts/build-development.sh. Public browser config only.\n"
    f"export const SUPABASE_URL = {json.dumps(url)};\n"
    f"export const SUPABASE_PUBLISHABLE_KEY = {json.dumps(key)};\n"
    'export const TODAYFOREST_ENVIRONMENT = "development";\n',
    encoding="utf-8",
)
PY

printf 'Built development artifact: %s\n' "$DEV_DIST_DIR"
